from holosoma.config_types.algo import (
    FastSACAlgoConfig,
    FastSACConfig,
    FlashSACVendorAlgoConfig,
    FlashSACVendorConfig,
    FPOAlgoConfig,
    FPOConfig,
    FPOModuleDictConfig,
    LayerConfig,
    ModuleConfig,
    OptimizerConfig,
    PPOAlgoConfig,
    PPOConfig,
    PPOModuleDictConfig,
)

ppo = PPOAlgoConfig(
    _target_="holosoma.agents.ppo.ppo.PPO",
    _recursive_=False,
    config=PPOConfig(
        num_learning_epochs=8,
        num_mini_batches=4,
        clip_param=0.2,
        gamma=0.99,
        lam=0.95,
        value_loss_coef=1.0,
        entropy_coef=0.01,
        actor_learning_rate=1e-5,
        actor_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        critic_learning_rate=1e-5,
        critic_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        max_grad_norm=1.0,
        schedule="adaptive",
        desired_kl=0.01,
        use_symmetry=True,
        symmetry_actor_coef=1.0,
        symmetry_critic_coef=0.0,
        num_steps_per_env=24,
        save_interval=100,
        load_optimizer=True,
        init_noise_std=0.8,
        num_learning_iterations=1000000,
        init_at_random_ep_len=True,
        empirical_normalization=False,
        eval_callbacks=None,
        module_dict=PPOModuleDictConfig(
            actor=ModuleConfig(
                type="MLP",
                input_dim=["actor_obs"],
                output_dim=["robot_action_dim"],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
            critic=ModuleConfig(
                type="MLP",
                input_dim=["critic_obs"],
                output_dim=[1],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
        ),
    ),
)

fast_sac = FastSACAlgoConfig(
    _target_="holosoma.agents.fast_sac.fast_sac_agent.FastSACAgent",
    _recursive_=False,
    config=FastSACConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-4,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=8192,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

fpo = FPOAlgoConfig(
    _target_="holosoma.agents.fpo.fpo_agent.FPOAgent",
    _recursive_=False,
    config=FPOConfig(
        num_learning_epochs=3,
        num_mini_batches=4,
        clip_param=0.05,
        gamma=0.99,
        lam=0.95,
        value_loss_coef=1.0,
        entropy_coef=0.0,
        actor_learning_rate=1e-4,
        actor_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=1e-4, betas=(0.9, 0.95)),
        critic_learning_rate=1e-4,
        critic_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=1e-4, betas=(0.9, 0.95)),
        max_grad_norm=0.5,
        use_symmetry=True,
        symmetry_actor_coef=0.0,
        symmetry_critic_coef=0.0,
        num_steps_per_env=24,
        save_interval=100,
        load_optimizer=True,
        num_learning_iterations=1000000,
        init_at_random_ep_len=True,
        eval_callbacks=None,
        time_embed_dim=64,
        use_ada_ln=True,
        num_flow_steps=64,
        num_mc_samples=16,
        ratio_mode="per_sample",
        ratio_log_clip=0.5,
        action_bound=3.0,
        cfm_reg_coef=0.0,
        cfm_reg_ema_beta=0.99,
        onnx_export_num_flow_steps=None,
        trust_region_mode="aspo",
        cfm_loss_clip=None,
        mc_chunk_size=16,
        module_dict=FPOModuleDictConfig(
            actor=ModuleConfig(
                type="MLP",
                input_dim=["actor_obs"],
                output_dim=["robot_action_dim"],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
            critic=ModuleConfig(
                type="MLP",
                input_dim=["critic_obs"],
                output_dim=[1],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
        ),
    ),
)

fpo_pp = FPOAlgoConfig(
    _target_="holosoma.agents.fpo.fpo_agent.FPOAgent",
    _recursive_=False,
    config=FPOConfig(
        # FPO++ official canonical hyperparameters
        num_learning_epochs=16,
        num_mini_batches=4,
        clip_param=0.05,
        gamma=0.99,
        lam=0.95,
        value_loss_coef=1.0,
        entropy_coef=0.0,
        actor_learning_rate=1e-4,
        actor_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=1e-4, betas=(0.9, 0.999)),
        critic_learning_rate=1e-4,
        critic_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=1e-4, betas=(0.9, 0.999)),
        max_grad_norm=1.0,
        use_symmetry=False,
        symmetry_actor_coef=0.0,
        symmetry_critic_coef=0.0,
        num_steps_per_env=24,
        save_interval=50,
        load_optimizer=True,
        num_learning_iterations=1000000,
        init_at_random_ep_len=True,
        eval_callbacks=None,
        # Flow model configuration (FPO++ style: simple MLP, raw sinusoidal embed)
        time_embed_dim=8,
        use_ada_ln=False,
        num_flow_steps=64,
        num_mc_samples=16,
        ratio_mode="per_sample",
        ratio_log_clip=0.5,
        action_bound=3.0,  # kept for backward compat; not used when use_tanh=False
        cfm_reg_coef=0.0,
        cfm_reg_ema_beta=0.99,
        onnx_export_num_flow_steps=None,
        trust_region_mode="aspo",
        cfm_loss_clip=20.0,
        mc_chunk_size=16,
        cfm_loss_reduction="sqrt",
        obs_normalization=True,
        # FPO++ specific
        use_tanh=False,
        actor_scale=1.0,
        action_perturb_std=0.02,
        storage_action_noise_std=0.0,
        cfm_loss_t_inverse_cdf_beta=1.0,
        use_learned_time_embed=False,
        mlp_output_scale=1.0,
        final_layer_weight_scale=None,
        use_ste_clamp=True,
        cfm_diff_clamp_max=10.0,
        cfm_loss_clamp_negative_advantages=True,
        cfm_loss_clamp_negative_advantages_max=20.0,
        advantage_clamp=(100.0, 100.0),
        knn_entropy_coef=0.0,
        knn_entropy_k=1,
        use_clipped_value_loss=False,
        ema_decay=0.95,
        ema_warmup_steps=500,
        flow_param_mode="velocity",
        module_dict=FPOModuleDictConfig(
            actor=ModuleConfig(
                type="MLP",
                input_dim=["actor_obs"],
                output_dim=["robot_action_dim"],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
            critic=ModuleConfig(
                type="MLP",
                input_dim=["critic_obs"],
                output_dim=[1],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
        ),
    ),
)

flash_sac = FlashSACVendorAlgoConfig(
    _target_="holosoma.agents.flash_sac.flash_sac_agent.FlashSACAgent",
    _recursive_=False,
    config=FlashSACVendorConfig(
        # Holosoma loop cadence (NOT in upstream FlashSAC).
        num_learning_iterations=50000,
        logging_interval=100,
        save_interval=1000,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
        # Defaults mirror configs/agent/flashSAC.yaml from upstream FlashSAC,
        # tuned for the GPU-simulator (IsaacLab) regime in scripts/run_isaaclab.sh.
        seed=0,
        normalize_reward=True,
        normalized_G_max=5.0,
        asymmetric_observation=False,
        device_type="cuda",
        buffer_max_length=10_000_000,
        buffer_min_length=100_000,
        buffer_device_type="cuda",
        sample_batch_size=2048,
        learning_rate_init=3e-4,
        learning_rate_peak=3e-4,
        learning_rate_end=1.5e-4,
        learning_rate_warmup_rate=1e-6,
        learning_rate_decay_rate=1.0,
        actor_num_blocks=2,
        actor_hidden_dim=128,
        actor_bc_alpha=0.0,
        actor_noise_zeta_mu=2.0,
        actor_noise_zeta_max=16,
        actor_update_period=2,
        critic_num_blocks=2,
        critic_hidden_dim=256,
        critic_num_bins=101,
        critic_min_v=-5.0,
        critic_max_v=5.0,
        critic_target_update_tau=0.01,
        temp_initial_value=0.01,
        temp_target_sigma=0.15,
        temp_target_entropy=None,
        gamma=0.99,
        n_step=3,
        use_compile=True,
        compile_mode="auto",
        use_amp=True,
        load_optimizer=True,
        load_reward_normalizer=True,
        updates_per_interaction_step=2.0,
    ),
)

DEFAULTS = {
    "ppo": ppo,
    "fast_sac": fast_sac,
    "flash_sac": flash_sac,
    "fpo": fpo,
    "fpo_pp": fpo_pp,
}
